lint:
  base_config: false
  files_exist: false
  files_unchanged: false
  modules_config: false
  multiqc_config: false
  nextflow_config:
    - custom_config
    - manifest.homePage
    - manifest.name
    - process.cpus
    - process.memory
    - process.time
  pipeline_name_conventions: false
  schema_lint: false
  template_strings:
    - bin/benchmark_report_template.html
    - assets/AGENTS.md
  nf_test_content:
    - tests/nextflow.config
nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: SciDev Team
  description: Pipeline to aggregate pertinent metrics across pipeline runs on the Seqera Platform.
  force: false
  is_nfcore: false
  name: nf-aggregate
  org: seqeralabs
  outdir: .
  skip_features:
    - ci
    - igenomes
    - nf_core_configs
  version: 0.7.0
